name: get deps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,11 * * 1-5"


jobs:
  update-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
            node-version: 18
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1
      - run: just download_deps Lunchtimecode
        env:
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r out.zip out
      - run: git config user.name SilenLoc
      - run: git config user.email silen.locatelli@gmx.ch
      - run: git add .
      - run: git commit -m "new deps"
      - run: git push