name: Get and publish deps

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6,11 * * 1-5"


jobs:
  update-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
      - uses: taiki-e/install-action@v2
        with:
          tool: just@1
          
      - name: Getting all deps
        run: just get_all_deps

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
            branch: gh-pages
            folder: public
            token: ${{ secrets.GITHUB_TOKEN }}
            single-commit: true